from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from unibot.public_safety import scan_public_files  # noqa: E402


EXTENSION_ROOT = ROOT / "unibot" / "browser_extension"


class UniBotBrowserExtensionTests(unittest.TestCase):
    def test_sidepanel_exposes_adaptive_task_flow(self) -> None:
        html = (EXTENSION_ROOT / "sidepanel.html").read_text(encoding="utf-8")
        script = (EXTENSION_ROOT / "sidepanel.js").read_text(encoding="utf-8")

        self.assertIn('id="adaptive"', html)
        self.assertIn("Uebungsaufgaben erzeugen", html)
        self.assertIn("/api/unibot/tasks/adaptive-plan", script)
        self.assertIn("skillSignalPatterns", script)
        self.assertIn("localSkillState", script)
        self.assertIn("offlineAdaptivePlan", script)
        self.assertIn("renderAdaptivePlan", script)
        self.assertIn("practice-only, no grade", script)

    def test_sidepanel_carries_release_review_board_claim_alignment(self) -> None:
        script = (EXTENSION_ROOT / "sidepanel.js").read_text(encoding="utf-8")

        self.assertIn("browserExtensionReleaseReviewBoardClaimAlignment", script)
        self.assertIn("unibot-browser-extension-release-review-board-claim-alignment-v1", script)
        self.assertIn("unibot-local-demo-release-review-board-claim-alignment-v1", script)
        self.assertIn("unibot-demo-feedback-release-review-board-claim-alignment-v1", script)
        self.assertIn("browser_extension_demo_handoff", script)
        self.assertIn("local_demo_run", script)
        self.assertIn("demo_feedback_contract", script)
        self.assertIn("human_submission_review_required", script)
        self.assertIn("exam clearance", script)
        self.assertIn("practice-only", script)

    def test_manifest_and_content_script_carry_boundary_claim_alignment(self) -> None:
        manifest = json.loads((EXTENSION_ROOT / "manifest.json").read_text(encoding="utf-8"))
        content = (EXTENSION_ROOT / "content.js").read_text(encoding="utf-8")

        self.assertEqual(["activeTab", "storage", "sidePanel"], manifest["permissions"])
        self.assertIn("https://colab.research.google.com/*", manifest["host_permissions"])
        self.assertIn("http://localhost/*", manifest["host_permissions"])
        self.assertIn("http://127.0.0.1/*", manifest["host_permissions"])
        self.assertNotIn("<all_urls>", json.dumps(manifest))
        self.assertIn("contentScriptBoundaryClaimAlignment", content)
        self.assertIn("unibot-browser-manifest-content-boundary-claim-alignment-v1", content)
        self.assertIn("unibot-browser-extension-release-review-board-claim-alignment-v1", content)
        self.assertIn("unibot-local-demo-release-review-board-claim-alignment-v1", content)
        self.assertIn("browser_manifest_content_boundary", content)
        self.assertIn("browser_extension_demo_handoff", content)
        self.assertIn("human_submission_review_required", content)
        self.assertIn("required_manifest_permissions", content)
        self.assertIn("Colab, localhost, and loopback practice surfaces only", content)
        self.assertIn("exam clearance", content)
        self.assertIn("never claims exam security", content)

    def test_browser_extension_does_not_depend_on_paperclip(self) -> None:
        manifest = json.loads((EXTENSION_ROOT / "manifest.json").read_text(encoding="utf-8"))
        html = (EXTENSION_ROOT / "sidepanel.html").read_text(encoding="utf-8")
        script = (EXTENSION_ROOT / "sidepanel.js").read_text(encoding="utf-8")
        content = (EXTENSION_ROOT / "content.js").read_text(encoding="utf-8")

        combined = "\n".join([json.dumps(manifest, ensure_ascii=False), html, script, content]).lower()

        self.assertNotIn("paperclip", combined)
        self.assertNotIn("paperclip.ing", combined)
        self.assertNotIn("/api/unibot/paperclip", combined)
        self.assertNotIn("https://paperclip", combined)
        self.assertEqual(["activeTab", "storage", "sidePanel"], manifest["permissions"])

    def test_sidepanel_exposes_demo_feedback_flow(self) -> None:
        html = (EXTENSION_ROOT / "sidepanel.html").read_text(encoding="utf-8")
        script = (EXTENSION_ROOT / "sidepanel.js").read_text(encoding="utf-8")

        self.assertIn('id="feedbackScenario"', html)
        self.assertIn('id="feedbackValidate"', html)
        self.assertIn('id="feedbackSave"', html)
        self.assertIn("Demo-Feedback", html)
        self.assertIn("/api/unibot/demo-feedback/validate", script)
        self.assertIn("/api/unibot/demo-feedback/append", script)
        self.assertIn("buildDemoFeedback", script)
        self.assertIn("validateFeedbackLocally", script)
        self.assertIn("renderFeedbackValidation", script)
        self.assertIn("private_data_removed", script)

    def test_sidepanel_exposes_command_center_flow(self) -> None:
        html = (EXTENSION_ROOT / "sidepanel.html").read_text(encoding="utf-8")
        script = (EXTENSION_ROOT / "sidepanel.js").read_text(encoding="utf-8")

        self.assertIn("Command Center", html)
        self.assertIn('id="commandCenter"', html)
        self.assertIn('id="compilerPlan"', html)
        self.assertIn('id="extractionQueue"', html)
        self.assertIn('id="decisionPacket"', html)
        self.assertIn('id="operatorPacket"', html)
        self.assertIn('id="privateExtractionRun"', html)
        self.assertIn('id="privateExtractionRunOcr"', html)
        self.assertIn('id="videoTranscriptionRun"', html)
        self.assertIn('id="extractionProgress"', html)
        self.assertIn('id="extractionReceiptJournal"', html)
        self.assertIn('id="extractionHumanReviewPlan"', html)
        self.assertIn('id="privateManifestApplyDryRun"', html)
        self.assertIn('id="privateTutorIndexDryRun"', html)
        self.assertIn('id="privateIndexTutorResponse"', html)
        self.assertIn('id="privateTutorUseFlow"', html)
        self.assertIn('id="notebookCell"', html)
        self.assertIn('id="notebookCheckpointAdapter"', html)
        self.assertIn('id="confirmCheckpointStore"', html)
        self.assertIn('id="confirmExamWorkspaceRun"', html)
        self.assertIn('id="confirmManifestApply"', html)
        self.assertIn('id="confirmTutorIndexBuild"', html)
        self.assertIn('id="confirmHelpLedgerAppend"', html)
        self.assertIn('id="confirmExamLedgerAppend"', html)
        self.assertIn('id="confirmTimelineExportReceiptJournalAppend"', html)
        self.assertIn('id="examWorkspaceRun"', html)
        self.assertIn('id="extractionDeferralValidate"', html)
        self.assertIn('id="extractionCompletionReport"', html)
        self.assertIn('id="extractionBatchPlan"', html)
        self.assertIn('id="extractionBatchPlanOcr"', html)
        self.assertIn('id="batchReceiptPacket"', html)
        self.assertIn('id="batchReceiptPacketOcr"', html)
        self.assertIn('id="manifestUpdatePlan"', html)
        self.assertIn('id="tutorCoveragePlan"', html)
        self.assertIn('id="materialCoverageRun"', html)
        self.assertIn('id="examSkillDrilldown"', html)
        self.assertIn('id="skillToWorkspaceRun"', html)
        self.assertIn('id="skillToWorkspaceSessionCarryover"', html)
        self.assertIn('id="examSessionConsole"', html)
        self.assertIn('id="examRunHistoryReview"', html)
        self.assertIn('id="examWorkspaceLaunchFlow"', html)
        self.assertIn('id="examWorkspaceOperatorRun"', html)
        self.assertIn('id="studySessionPlan"', html)
        self.assertIn('id="studyReceiptValidate"', html)
        self.assertIn('id="studyReviewReport"', html)
        self.assertIn('id="clearanceBoard"', html)
        self.assertIn('id="submissionBundle"', html)
        self.assertIn('id="decisionRequest"', html)
        self.assertIn('id="decisionRequestMarkdown"', html)
        self.assertIn('id="decisionJournal"', html)
        self.assertIn('id="decisionRecordJournal"', html)
        self.assertIn('id="decisionState"', html)
        self.assertIn('id="localDecisionIntake"', html)
        self.assertIn('id="localDecisionWorkspace"', html)
        self.assertIn('id="ocrFirstOperatorRun"', html)
        self.assertIn('id="courseExamCoverageDashboard"', html)
        self.assertIn('id="perSkillActionRouter"', html)
        self.assertIn('id="executeRoutedAction"', html)
        self.assertIn('id="examRunPacket"', html)
        self.assertIn('id="examPacketTimeline"', html)
        self.assertIn('id="timelineExportReviewPacket"', html)
        self.assertIn('id="timelineExportReceiptJournalAppend"', html)
        self.assertIn('id="timelineExportReceiptJournalSummary"', html)
        self.assertIn('id="reviewChainIntegrityCheck"', html)
        self.assertIn('id="pythonExamReadinessConsole"', html)
        self.assertIn('id="pythonExamCockpitFlow"', html)
        self.assertIn('id="pythonExamLiveControlSurface"', html)
        self.assertIn('id="pythonExamEvidenceExportPreview"', html)
        self.assertIn('id="pythonExamTutorDrillPack"', html)
        self.assertIn('id="pythonExamDrillSessionRunner"', html)
        self.assertIn('id="pythonExamDrillSessionReviewLoop"', html)
        self.assertIn('id="pythonExamDrillLoopControlPanel"', html)
        self.assertIn('id="pythonExamDrillLoopProgressJournal"', html)
        self.assertIn('id="pythonExamResumeLauncher"', html)
        self.assertIn('id="pythonExamActiveStudyLoopDashboard"', html)
        self.assertIn('id="pythonExamActiveStudyGuidedRunner"', html)
        self.assertIn('id="pythonExamGuidedActionExecutionBridge"', html)
        self.assertIn('id="pythonExamSafeCycleConsole"', html)
        self.assertIn('id="pythonExamSafeCycleOperatorGate"', html)
        self.assertIn('id="pythonExamOperatorGateDecisionReceipt"', html)
        self.assertIn('id="pythonExamLocalCycleStartPacket"', html)
        self.assertIn('id="pythonExamLocalCycleReadinessReview"', html)
        self.assertIn('id="pythonExamLocalCycleReadinessHandoff"', html)
        self.assertIn('id="pythonExamLocalCycleWorkspaceCard"', html)
        self.assertIn('id="pythonExamLocalCycleChainSnapshot"', html)
        self.assertIn('id="pythonExamManualConfirmationConsole"', html)
        self.assertIn('id="pythonExamManualCycleLaunchReceipt"', html)
        self.assertIn('id="confirmDrillLoopProgressJournalAppend"', html)
        self.assertIn('id="pythonExamConfirmedLocalExportDraft"', html)
        self.assertIn('id="pythonExamDraftPackageReviewConsole"', html)
        self.assertIn('id="pythonExamFullLocalRehearsalPack"', html)
        self.assertIn('id="pythonExamFinalManualReviewActionLock"', html)
        self.assertIn('id="pythonExamLockedFinalReviewBoard"', html)
        self.assertIn('id="pythonExamLockedFinalReviewGapResolver"', html)
        self.assertIn('id="confirmLocalExportDraftWrite"', html)
        self.assertIn('id="contextPacket"', html)
        self.assertIn("/api/unibot/orchestration/command-center", script)
        self.assertIn("/api/unibot/course/compiler-plan", script)
        self.assertIn("/api/unibot/course/extraction-queue", script)
        self.assertIn("/api/unibot/course/extraction-decision-packet", script)
        self.assertIn("/api/unibot/course/extraction-decision/local-intake", script)
        self.assertIn("/api/unibot/course/extraction-decision/workspace/prepare", script)
        self.assertIn("/api/unibot/course/extraction-operator-packet", script)
        self.assertIn("/api/unibot/course/private-extraction/run-batch", script)
        self.assertIn("/api/unibot/course/ocr-first/operator-run", script)
        self.assertIn("/api/unibot/course/video-transcription/run-batch", script)
        self.assertIn("privateExtractionRunOcr", script)
        self.assertIn("decision_record_journal_path", script)
        self.assertIn("receipt_journal_path", script)
        self.assertIn("/api/unibot/course/extraction-progress-report", script)
        self.assertIn("/api/unibot/course/extraction-receipts/summary", script)
        self.assertIn("/api/unibot/course/extraction-review/apply-plan", script)
        self.assertIn("/api/unibot/course/extraction-manifest/apply-dry-run", script)
        self.assertIn("/api/unibot/course/tutor-index/dry-run", script)
        self.assertIn("/api/unibot/course/tutor-index/respond-dry-run", script)
        self.assertIn("/api/unibot/course/private-tutor-use-flow/dry-run", script)
        self.assertIn("/api/unibot/exam-workspace/notebook-checkpoint/adapt", script)
        self.assertIn("/api/unibot/exam-workspace/operator-run", script)
        self.assertIn("/api/unibot/exam-workspace/session-console", script)
        self.assertIn("/api/unibot/exam-workspace/run-history-export-review", script)
        self.assertIn("/api/unibot/course/exam-coverage-dashboard", script)
        self.assertIn("/api/unibot/course/per-skill-action-router", script)
        self.assertIn("/api/unibot/course/routed-action-executor", script)
        self.assertIn("/api/unibot/course/exam-run-packet", script)
        self.assertIn("/api/unibot/course/exam-packet-timeline", script)
        self.assertIn("/api/unibot/course/timeline-export-review-packet", script)
        self.assertIn("/api/unibot/course/timeline-export-receipt-journal/append", script)
        self.assertIn("/api/unibot/course/timeline-export-receipt-journal/summary", script)
        self.assertIn("/api/unibot/course/review-chain-integrity-check", script)
        self.assertIn("/api/unibot/course/python-exam-readiness-console", script)
        self.assertIn("/api/unibot/course/python-exam-cockpit-flow", script)
        self.assertIn("/api/unibot/course/python-exam-live-control-surface", script)
        self.assertIn("/api/unibot/course/python-exam-evidence-export-preview", script)
        self.assertIn("/api/unibot/course/python-exam-source-grounded-tutor-drill-pack", script)
        self.assertIn("/api/unibot/course/python-exam-drill-session-runner", script)
        self.assertIn("/api/unibot/course/python-exam-drill-session-review-loop", script)
        self.assertIn("/api/unibot/course/python-exam-drill-loop-control-panel", script)
        self.assertIn("/api/unibot/course/python-exam-drill-loop-progress-journal", script)
        self.assertIn("/api/unibot/course/python-exam-resume-launcher", script)
        self.assertIn("/api/unibot/course/python-exam-active-study-loop-dashboard", script)
        self.assertIn("/api/unibot/course/python-exam-active-study-guided-runner", script)
        self.assertIn("/api/unibot/course/python-exam-guided-action-execution-bridge", script)
        self.assertIn("/api/unibot/course/python-exam-safe-cycle-console", script)
        self.assertIn("/api/unibot/course/python-exam-safe-cycle-operator-gate", script)
        self.assertIn("/api/unibot/course/python-exam-operator-gate-decision-receipt", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-start-packet", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-readiness-review", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-readiness-handoff", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-operator-workspace-card", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-chain-snapshot", script)
        self.assertIn("/api/unibot/course/python-exam-local-cycle-manual-confirmation-console", script)
        self.assertIn("/api/unibot/course/python-exam-manual-cycle-launch-receipt", script)
        self.assertIn("/api/unibot/course/python-exam-confirmed-local-export-draft", script)
        self.assertIn("/api/unibot/course/python-exam-draft-package-review-console", script)
        self.assertIn("/api/unibot/course/python-exam-full-local-rehearsal-pack", script)
        self.assertIn("/api/unibot/course/python-exam-rehearsal-playback-gap-coach", script)
        self.assertIn("/api/unibot/course/python-exam-gap-coach-guided-rehearsal-loop", script)
        self.assertIn("/api/unibot/course/python-exam-guided-loop-control-surface", script)
        self.assertIn("/api/unibot/exam-workspace/run-dry-run", script)
        self.assertIn("/api/unibot/course/extraction-deferral/validate", script)
        self.assertIn("/api/unibot/course/extraction-completion-report", script)
        self.assertIn("/api/unibot/course/extraction-batch-plan", script)
        self.assertIn("/api/unibot/course/extraction-batch-receipt-packet", script)
        self.assertIn('job_types: ["ocr"]', script)
        self.assertIn("/api/unibot/course/extraction-manifest-update-plan", script)
        self.assertIn("/api/unibot/course/tutor-coverage-plan", script)
        self.assertIn("/api/unibot/course/material-coverage/run", script)
        self.assertIn("/api/unibot/course/exam-skill-drilldown", script)
        self.assertIn("/api/unibot/course/skill-to-workspace-live-flow", script)
        self.assertIn("/api/unibot/course/skill-to-workspace-session-carryover", script)
        self.assertIn("/api/unibot/exam-workspace/launch-flow/dry-run", script)
        self.assertIn("/api/unibot/course/study-session-plan", script)
        self.assertIn("/api/unibot/course/study-session-receipt/validate", script)
        self.assertIn("/api/unibot/course/study-session-review-report", script)
        self.assertIn("/api/unibot/institutional-clearance/board", script)
        self.assertIn("/api/unibot/stakeholder/submission-bundle", script)
        self.assertIn("/api/unibot/stakeholder/decision-request", script)
        self.assertIn("/api/unibot/stakeholder/decision-request-markdown", script)
        self.assertIn("/api/unibot/stakeholder/decision-journal/summary", script)
        self.assertIn("/api/unibot/stakeholder/decision-record-journal/summary", script)
        self.assertIn("/api/unibot/stakeholder/decision-state", script)
        self.assertIn("/api/unibot/orchestration/context-packet", script)
        self.assertIn("renderCommandCenter", script)
        self.assertIn("renderCompilerPlan", script)
        self.assertIn("renderPythonExamFullLocalRehearsalPack", script)
        self.assertIn("renderExtractionQueue", script)
        self.assertIn("renderDecisionPacket", script)
        self.assertIn("renderOperatorPacket", script)
        self.assertIn("renderPrivateExtractionRun", script)
        self.assertIn("renderVideoTranscriptionRun", script)
        self.assertIn("renderExtractionProgress", script)
        self.assertIn("renderExtractionReceiptJournal", script)
        self.assertIn("renderExtractionHumanReviewPlan", script)
        self.assertIn("renderPrivateManifestApplyDryRun", script)
        self.assertIn("renderPrivateTutorIndexDryRun", script)
        self.assertIn("renderPrivateIndexTutorResponse", script)
        self.assertIn("renderPrivateTutorUseFlow", script)
        self.assertIn("renderNotebookCheckpointAdapter", script)
        self.assertIn("renderExamWorkspaceRun", script)
        self.assertIn("renderExamWorkspaceOperatorRun", script)
        self.assertIn("renderExtractionDeferralValidation", script)
        self.assertIn("renderExtractionCompletionReport", script)
        self.assertIn("renderExtractionBatchPlan", script)
        self.assertIn("renderBatchReceiptPacket", script)
        self.assertIn("renderManifestUpdatePlan", script)
        self.assertIn("renderTutorCoveragePlan", script)
        self.assertIn("renderMaterialCoverageRun", script)
        self.assertIn("renderExamSkillDrilldown", script)
        self.assertIn("renderSkillToWorkspaceLiveFlow", script)
        self.assertIn("skillWorkspaceLiveFlowPayload", script)
        self.assertIn("renderSkillToWorkspaceSessionCarryover", script)
        self.assertIn("skillWorkspaceSessionCarryoverPayload", script)
        self.assertIn("skillWorkspaceOperatorPayload", script)
        self.assertIn("renderExamSessionConsole", script)
        self.assertIn("skillWorkspaceSessionConsolePayload", script)
        self.assertIn("Exam Workspace Session Console", script)
        self.assertIn("Local Cycle Card", script)
        self.assertIn("renderExamRunHistoryReview", script)
        self.assertIn("Run-History Export Review", script)
        self.assertIn("Workspace cards:", script)
        self.assertIn("renderCourseExamCoverageDashboard", script)
        self.assertIn("Course Exam Coverage Dashboard", script)
        self.assertIn("renderPerSkillActionRouter", script)
        self.assertIn("Per-Skill Action Router", script)
        self.assertIn("renderRoutedActionExecutor", script)
        self.assertIn("Routed Action Executor", script)
        self.assertIn("renderExamRunPacket", script)
        self.assertIn("Exam Run Packet", script)
        self.assertIn("renderExamPacketTimeline", script)
        self.assertIn("Exam Packet Timeline", script)
        self.assertIn("renderTimelineExportReviewPacket", script)
        self.assertIn("Timeline Export Review Packet", script)
        self.assertIn("renderTimelineExportReceiptJournalAppend", script)
        self.assertIn("renderTimelineExportReceiptJournalSummary", script)
        self.assertIn("renderReviewChainIntegrityCheck", script)
        self.assertIn("Review Chain Integrity", script)
        self.assertIn("renderPythonExamReadinessConsole", script)
        self.assertIn("Python Exam Readiness Console", script)
        self.assertIn("renderPythonExamCockpitFlow", script)
        self.assertIn("Python Exam Cockpit Flow", script)
        self.assertIn("renderPythonExamLiveControlSurface", script)
        self.assertIn("Python Exam Live Control Surface", script)
        self.assertIn("renderPythonExamEvidenceExportPreview", script)
        self.assertIn("Python Exam Evidence Export Preview", script)
        self.assertIn("renderPythonExamTutorDrillPack", script)
        self.assertIn("Python Exam Tutor Drill Pack", script)
        self.assertIn("renderPythonExamDrillSessionRunner", script)
        self.assertIn("Python Exam Drill Session", script)
        self.assertIn("renderPythonExamDrillSessionReviewLoop", script)
        self.assertIn("Python Exam Drill Review Loop", script)
        self.assertIn("renderPythonExamDrillLoopControlPanel", script)
        self.assertIn("Python Exam Drill Control Panel", script)
        self.assertIn("renderPythonExamDrillLoopProgressJournal", script)
        self.assertIn("Python Exam Drill Progress Journal", script)
        self.assertIn("renderPythonExamResumeLauncher", script)
        self.assertIn("Python Exam Resume Launcher", script)
        self.assertIn("renderPythonExamActiveStudyLoopDashboard", script)
        self.assertIn("Python Exam Active Study Loop", script)
        self.assertIn("renderPythonExamActiveStudyGuidedRunner", script)
        self.assertIn("Python Exam Guided Runner", script)
        self.assertIn("renderPythonExamGuidedActionExecutionBridge", script)
        self.assertIn("Python Exam Execution Bridge", script)
        self.assertIn("renderPythonExamSafeCycleConsole", script)
        self.assertIn("Python Exam Safe Cycle Console", script)
        self.assertIn("renderPythonExamSafeCycleOperatorGate", script)
        self.assertIn("Python Exam Operator Gate", script)
        self.assertIn("renderPythonExamOperatorGateDecisionReceipt", script)
        self.assertIn("Python Exam Gate Decision Receipt", script)
        self.assertIn("renderPythonExamLocalCycleStartPacket", script)
        self.assertIn("Python Exam Local Cycle Start Packet", script)
        self.assertIn("renderPythonExamLocalCycleReadinessReview", script)
        self.assertIn("Python Exam Local Cycle Readiness Review", script)
        self.assertIn("renderPythonExamLocalCycleReadinessHandoff", script)
        self.assertIn("Python Exam Local Cycle Handoff", script)
        self.assertIn("renderPythonExamLocalCycleOperatorWorkspaceCard", script)
        self.assertIn("Python Exam Local Cycle Workspace", script)
        self.assertIn("renderPythonExamLocalCycleChainSnapshot", script)
        self.assertIn("Python Exam Local Cycle Chain Snapshot", script)
        self.assertIn("renderPythonExamManualConfirmationConsole", script)
        self.assertIn("Python Exam Manual Confirmation Console", script)
        self.assertIn("renderPythonExamManualCycleLaunchReceipt", script)
        self.assertIn("Python Exam Manual Cycle Launch Receipt", script)
        self.assertIn("renderPythonExamManualCycleEvidenceBinder", script)
        self.assertIn("Python Exam Manual Cycle Evidence Binder", script)
        self.assertIn("renderPythonExamManualPostCycleReceiptIntake", script)
        self.assertIn("Python Exam Manual Post-Cycle Receipt Intake", script)
        self.assertIn("renderPythonExamManualCycleClosureLedger", script)
        self.assertIn("Python Exam Manual Cycle Closure Ledger", script)
        self.assertIn("renderPythonExamManualCycleReviewTimeline", script)
        self.assertIn("Python Exam Manual Cycle Review Timeline", script)
        self.assertIn("renderPythonExamManualCycleReviewPacket", script)
        self.assertIn("Python Exam Manual Cycle Review Packet", script)
        self.assertIn("renderPythonExamManualReviewExportPreview", script)
        self.assertIn("Python Exam Manual Review Export Preview", script)
        self.assertIn("renderPythonExamManualReviewExportAuthorizationGate", script)
        self.assertIn("Python Exam Export Authorization Gate", script)
        self.assertIn("renderPythonExamManualExportReviewQueue", script)
        self.assertIn("Python Exam Export Review Queue", script)
        self.assertIn("renderPythonExamManualExportReviewerPacket", script)
        self.assertIn("Python Exam Export Reviewer Packet", script)
        self.assertIn("renderPythonExamManualArchiveDecisionDraft", script)
        self.assertIn("Python Exam Archive Decision Draft", script)
        self.assertIn("renderPythonExamManualFinalReviewHandoff", script)
        self.assertIn("Python Exam Final Review Handoff", script)
        self.assertIn("renderPythonExamManualFinalReviewReceiptLedger", script)
        self.assertIn("Python Exam Final Review Receipt Ledger", script)
        self.assertIn("renderPythonExamFinalReviewLedgerIntegrityGate", script)
        self.assertIn("Python Exam Final Review Ledger Integrity Gate", script)
        self.assertIn("renderPythonExamFinalManualReviewConsole", script)
        self.assertIn("Python Exam Final Review Console", script)
        self.assertIn("renderPythonExamFinalManualReviewActionLock", script)
        self.assertIn("Python Exam Final Action Lock", script)
        self.assertIn("renderPythonExamLockedFinalReviewBoard", script)
        self.assertIn("Python Exam Locked Final Review Board", script)
        self.assertIn("renderPythonExamLockedFinalReviewGapResolver", script)
        self.assertIn("Python Exam Final Gap Resolver", script)
        self.assertIn("renderPythonExamConfirmedLocalExportDraft", script)
        self.assertIn("Python Exam Confirmed Local Export Draft", script)
        self.assertIn("renderPythonExamDraftPackageReviewConsole", script)
        self.assertIn("Python Exam Draft Package Review Console", script)
        self.assertIn("renderPythonExamFullLocalRehearsalPack", script)
        self.assertIn("Python Exam Full Local Rehearsal", script)
        self.assertIn("renderPythonExamRehearsalPlaybackGapCoach", script)
        self.assertIn("Python Exam Gap Coach", script)
        self.assertIn("renderPythonExamGapCoachGuidedLoop", script)
        self.assertIn("Python Exam Guided Loop", script)
        self.assertIn("renderPythonExamGuidedLoopControlSurface", script)
        self.assertIn("Python Exam Loop Control", script)
        self.assertIn("ready_to_execute_operator_dry_run", script)
        self.assertIn("Skill-to-Workspace Live Flow", script)
        self.assertIn("Skill-to-Workspace Session Carryover", script)
        self.assertIn("renderExamWorkspaceLaunchFlow", script)
        self.assertIn("renderStudySessionPlan", script)
        self.assertIn("renderStudyReceiptValidation", script)
        self.assertIn("renderStudyReviewReport", script)
        self.assertIn("renderClearanceBoard", script)
        self.assertIn("renderSubmissionBundle", script)
        self.assertIn("renderDecisionRequest", script)
        self.assertIn("Decision-Request Markdown kopiert", script)
        self.assertIn("renderDecisionJournal", script)
        self.assertIn("renderDecisionRecordJournal", script)
        self.assertIn("renderDecisionState", script)
        self.assertIn("renderContextPacket", script)
        self.assertIn("Context Packet JSON kopiert", script)

    def test_extension_manifest_and_public_files_are_safe(self) -> None:
        manifest = json.loads((EXTENSION_ROOT / "manifest.json").read_text(encoding="utf-8"))
        files = sorted(path for path in EXTENSION_ROOT.glob("*") if path.is_file())
        scan = scan_public_files(files)

        self.assertEqual(manifest["manifest_version"], 3)
        self.assertIn("sidePanel", manifest["permissions"])
        self.assertIn("https://colab.research.google.com/*", manifest["host_permissions"])
        self.assertEqual(scan["status"], "pass", scan["findings"])


if __name__ == "__main__":
    unittest.main()
